language: python
stages:
- build
- check
- deploy

branches:
  except:
  - gh-pages

addons:
  apt:
    packages:
    - graphviz
    - shellcheck
    - python-pip

before_install:
- pip install -U pip
- pip install pylint
install:
- make install

jobs:
  include:
  - stage: build
    name: Build Python Package
    install: true
    script:
    - make release-build
    - make install

  - stage: check
    name: "Lint / Style check (bin)"
    script:
    - pylint bin/cij_fetch
    - pylint bin/cij_reporter
    - pylint bin/cij_runner
    - pylint bin/cij_tlint
    - pylint bin/config_add_opts
    - pylint bin/fio_plot
    - pylint bin/rand_str
    - shellcheck bin/cijoe modules/*.sh
    - shellcheck bin/cij_root
    - shellcheck bin/nvm_prep

  - stage: check
    name: "Lint / Style check (SHELL modules)"
    script:
      - shellcheck modules/*.sh

  - stage: check
    name: "Lint / Style check (Python modules)"
    script:
      - pylint modules/cij

  - stage: check
    name: "Lint / Style check (built-in testcase, testsuite, and testplans)"
    script:
      - CIJ_ROOT=$(cij_root) cij_tlint

  - stage: deploy
    script: true
    deploy:
      provider: pypi
      user: safl@safl.dk
      password:
        secure: "fVHtFCrbO0kWcdrXxTr52ObmEAF/Cxp2tqGWOw0XCSZOX0m7sekfQT++9264vS/HKE9FjOdP8/CnLhqodl5D7sJ9iQmYr/+iA4c+RBZRbdBUi52CXR3dmxaQVWF3ZGkgF2/Z5LituHuedaiO+UMC/Ahwnrt42rIdHdBS/SJpArPNYqOG7u+2FSTL7Ar2aiWVxV0UDOSv/jfav3VN7denZ+QgWX100+zgvyy8fYn3iAyVQNP0vHyFJZzo78v5nKPCS2bPFtHxmDeNIv8XKq1U7KxR3Jz3XzJUd02zLAAhoZyf21VPQtidNQUUqjF1OdzDXaoz2SD0KH2s5naeiW8k06UdHlElDyK0RlgphCZDtI1/ppcAujh0CzNzbnfvm96BUIAQxdlUJazUUpyV8JAhPwgXZCc6PsKFMlL+Dlrqs/5ViJ8C3+VK0t8kfK6i2PcT7IlxKSquBrxn3b1GMxoZrwRfadvXW5aaJjj+BgI7f3LlZLwsp9bHS6uQ1btFpZcxgdh5mBM+4Gm5wvE8e8W68/wE00CwMqbgvvinL66o6OEinhB+Gouy9zHo8ud9Bpbn2kuE1X1afJmSd6X86rxorOE5L8ffQraZ6cT+g2J4VHkodXqU75px2qRl8EWgiotN+XdmUqeQo8yqDjIhQ22nRZJkSOdmK5rC2yWvlHGoNHQ="
      on:
        tags: true
